import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ImKey2 } from "react-icons/im";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/toaster";
import { AuthContext } from "../contexts/AuthContext";
import { ErrorToaster } from "@/components/common/ErrorToaster";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "認証システム",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${inter.className} p-1 h-screen2`}>
        <div className="space-y-8 pb-8">
          <div>
            <Link className="flex items-center space-x-1 text-2xl" href={"/"}>
              <ImKey2 />
              <h1 className="text-2xl font-bold text-gray-900">Next Auth Login System</h1>
            </Link>
          </div>
          <p className="text-lg text-gray-700">
            Next.jsとNextAuthを使用したログインシステムの構築
          </p>
        </div>
        <Separator />
        <div className="pt-4">
          <AuthContext>{children}</AuthContext>
        </div>
        <Toaster />
        <ErrorToaster />
      </body>
    </html>
  );
}
